pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/SuvarnaWadne/petstore-api-automation.git',
                    credentialsId: 'github-pat-credentials'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat "mvn clean install -DskipTests"
            }
        }

        stage('Run Tests') {
            steps {
                bat "mvn test"
            }
        }

        stage('Publish TestNG Results') {
            steps {
                echo "Publishing TestNG XML report..."
                junit 'test-output/testng-results.xml'
            }
        }

        stage('Publish HTML Report') {
            steps {
                echo "Publishing TestNG HTML Report..."
                publishHTML target: [
                    reportDir: 'test-output',
                    reportFiles: 'index.html',
                    reportName: 'TestNG HTML Report'
                ]
            }
        }

        stage('Archive Screenshots / Reports') {
            steps {
                echo "Archiving screenshots and reports..."
                archiveArtifacts artifacts: 'test-output/**/*.*', allowEmptyArchive: true
            }
        }

    }

    post {
        always {
            echo "Pipeline Finished"
        }
        success {
            echo "All Tests Passed!"
        }
        failure {
            echo "Some Tests Failed!"
        }
    }
}
