pipeline {
    agent any

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/SuvarnaWadne/petstore-api-automation.git',
                    credentialsId: 'github-pat-credentials'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat 'mvn clean install -DskipTests'
            }
        }

        stage('Run Tests') {
            steps {
                bat 'mvn test'
            }
        }

        stage('Publish TestNG Report') {
            steps {
                publishTestNGResults testResults: 'target/surefire-reports/testng-results.xml'
            }
        }

        stage('Archive Reports for Client') {
            steps {
                archiveArtifacts artifacts: 'target/surefire-reports/**/*.xml', allowEmptyArchive: false
                archiveArtifacts artifacts: 'test-output/**', allowEmptyArchive: true
            }
        }
    }

    post {
        always {
            echo "Pipeline execution completed!"
        }
    }
}
